### ISSUE TITLE
docker-compose not working with AM 7.1.2 and Amster 7.1.2 (updated: also with 7.0.1)

### ISSUE THREAD

**Issue by alberttra** [ForgeRock/frdp-containers-uma#9]
when running `docker-compose up --build` i got this following issue:

```
[+] Building 12.7s (20/20) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/tomcat:9-jdk11-adoptopenjdk-hotspot                                                                       1.6s
 => [ 1/16] FROM docker.io/library/tomcat:9-jdk11-adoptopenjdk-hotspot@sha256:1cac44feaa72ca0937995084a25512c43161c84bcb651ff4623977d96a31fa89               0.0s
 => [internal] load build context                                                                                                                            0.0s
 => => transferring context: 2.23kB                                                                                                                          0.0s
 => CACHED [ 2/16] RUN apt-get update -y &&     apt-get install -y binutils wget unzip curl                                                                  0.0s
 => CACHED [ 3/16] RUN rm -rf "/usr/local/tomcat"/webapps/*                                                                                                  0.0s
 => CACHED [ 4/16] ADD build/resources/am.war /usr/local/tomcat/webapps/am.war                                                                               0.0s
 => CACHED [ 5/16] ADD build/resources/amster.zip /tmp/amster.zip                                                                                            0.0s
 => CACHED [ 6/16] RUN mkdir -p /opt/forgerock/amster &&     unzip -q /tmp/amster.zip -d /opt/forgerock/amster                                               0.0s
 => CACHED [ 7/16] ADD build/amster/install-am.amster /opt/forgerock/amster/install-am.amster                                                                0.0s
 => CACHED [ 8/16] ADD build/amster/import-config.amster /opt/forgerock/amster/import-config.amster                                                          0.0s
 => CACHED [ 9/16] ADD build/amster/export-config.amster /opt/forgerock/amster/export-config.amster                                                          0.0s
 => CACHED [10/16] ADD build/amster/am-config /opt/forgerock/am/configuration                                                                                0.0s
 => CACHED [11/16] ADD build/amster/am-snapshot /opt/forgerock/am/snapshot                                                                                   0.0s
 => CACHED [12/16] ADD build/users.sh /opt/forgerock/am/users.sh                                                                                             0.0s
 => CACHED [13/16] ADD build/commands.sh /opt/forgerock/am/commands.sh                                                                                       0.0s
 => CACHED [14/16] RUN chmod a+x /opt/forgerock/am/commands.sh /opt/forgerock/am/users.sh                                                                    0.0s
 => CACHED [15/16] RUN /bin/bash -c "echo "source /opt/forgerock/am/commands.sh" >> /root/.bashrc"                                                           0.0s
 => ERROR [16/16] RUN /bin/bash -c     "source /opt/forgerock/am/commands.sh && install_am && configure_am && load_users && stop_tomcat"                    11.1s
------
 > [16/16] RUN /bin/bash -c     "source /opt/forgerock/am/commands.sh && install_am && configure_am && load_users && stop_tomcat":
#20 0.156 Tomcat started.
#20 0.156
#20 0.156 Waiting for server startup.....
#20 10.18 Server started
#20 10.18 Installing AM
#20 10.97 Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi64-7.1.2 - 2022-Mar-11 19:48:22 in java.library.path: [/usr/local/tomcat/native-jni-lib, /usr/java/packages/lib, /lib, /usr/lib], no jansi-7.1.2 - 2022-Mar-11 19:48:22 in java.library.path: [/usr/local/tomcat/native-jni-lib, /usr/java/packages/lib, /lib, /usr/lib], no jansi in java.library.path: [/usr/local/tomcat/native-jni-lib, /usr/java/packages/lib, /lib, /usr/lib], /tmp/libjansi-64-7-16511872525821548782.1: /tmp/libjansi-64-7-16511872525821548782.1: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)]
#20 10.97 	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
#20 10.97 	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
#20 10.97 	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
#20 10.97 	at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
#20 10.97 	at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
#20 10.97 	at java.base/java.lang.Class.forName0(Native Method)
#20 10.97 	at java.base/java.lang.Class.forName(Class.java:398)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.lambda$createCallStaticSite$2(CallSiteArray.java:65)
#20 10.97 	at java.base/java.security.AccessController.doPrivileged(Native Method)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:63)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:156)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
#20 10.97 	at org.apache.groovy.groovysh.Main.installAnsi(Main.groovy:249)
#20 10.97 	at org.apache.groovy.groovysh.Main$installAnsi$0.callStatic(Unknown Source)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:222)
#20 10.97 	at org.apache.groovy.groovysh.Main.setTerminalType(Main.groovy:235)
#20 10.97 	at org.apache.groovy.groovysh.Main$setTerminalType.callStatic(Unknown Source)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
#20 10.97 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
#20 10.97 	at org.apache.groovy.groovysh.Main.main(Main.groovy:120)
#20 10.97 	at org.forgerock.openam.amster.Main.main(Main.groovy:63)
#20 11.00 Amster Installation failed
------
executor failed running [/bin/sh -c /bin/bash -c     "source /opt/forgerock/am/commands.sh && install_am && configure_am && load_users && stop_tomcat"]: exit code: 1
ERROR: Service 'as' failed to build : Build failed
```

Platform:
- macOS 12.4
- Docker 4.7.1

**Comment by alberttra** [comment]
docker-compose run in mac intel, m1 will not work
